# Generated by Django 2.2.15 on 2021-09-20 08:10

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicMassages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=250, verbose_name='پیام از بخش')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیحات مختصر')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات جامع')),
                ('publish', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان به روز رسانی')),
                ('status', models.CharField(choices=[('draft', 'در انتظار'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'پیام های عمومی',
                'verbose_name_plural': 'پیام های عمومی',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='PrivateMassages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=250, verbose_name='پیام از بخش')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیحات مختصر')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات جامع')),
                ('publish', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان به روز رسانی')),
                ('status', models.CharField(choices=[('draft', 'در انتظار'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت انتشار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام های خصوصی',
                'verbose_name_plural': 'پیام های خصوصی',
                'ordering': ('-publish',),
            },
        ),
    ]
