# Generated by Django 2.2.15 on 2021-09-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
