# Generated by Django 2.2.15 on 2021-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210919_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.PositiveIntegerField(default=1, verbose_name='کد پستی'),
            preserve_default=False,
        ),
    ]
