# Generated by Django 2.2.15 on 2021-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد پستی'),
        ),
    ]
