# Generated by Django 2.2.15 on 2021-10-30 08:56

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, default='', max_length=200, verbose_name='نام دسته بندی')),
                ('name_fa', models.CharField(db_index=True, default='', max_length=200, verbose_name='نام دسته بندی')),
                ('slug_en', models.SlugField(default='', max_length=200, unique=True, verbose_name='slug')),
                ('slug_fa', models.SlugField(default='', max_length=200, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'دسته بندی پست',
                'verbose_name_plural': 'دسته بندی پست ها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='', max_length=250, verbose_name='عنوان')),
                ('title_fa', models.CharField(default='', max_length=250, verbose_name='عنوان')),
                ('slug_en', models.SlugField(default='', max_length=250, unique_for_date='publish', verbose_name='slug')),
                ('slug_fa', models.SlugField(default='', max_length=250, unique_for_date='publish', verbose_name='slug')),
                ('author_en', models.CharField(default='', max_length=250, verbose_name='نویسنده')),
                ('author_fa', models.CharField(default='', max_length=250, verbose_name='نویسنده')),
                ('image', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d', verbose_name='عکس اصلی')),
                ('short_description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات مختصر')),
                ('short_description_fa', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات مختصر')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات جامع')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان به روز رسانی')),
                ('status', models.CharField(choices=[('draft', 'در انتظار'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت انتشار')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='meta_title')),
                ('meta_description', models.TextField(blank=True, max_length=350, null=True, verbose_name='meta_description')),
                ('meta_keywords', models.TextField(blank=True, max_length=350, null=True, verbose_name='meta_keywords')),
                ('alt_image', models.TextField(blank=True, max_length=350, null=True, verbose_name='alt_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.PostCategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='دیدگاه مورد نظر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان به روز رسانی')),
                ('active', models.BooleanField(default=False, verbose_name='فعال بودن نمایش دیدگاه در سایت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post', verbose_name='پست مورد نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دیدگاه های پست',
                'verbose_name_plural': 'دیدگاه های پست ها',
                'ordering': ('created',),
            },
        ),
    ]
