# Generated by Django 2.2.15 on 2021-10-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug_en',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='slug_en',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_fa',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='slug_fa',
        ),
    ]
