# Generated by Django 2.2.15 on 2021-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200718_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن نمایش دیدگاه در سایت'),
        ),
    ]
