# Generated by Django 2.2.15 on 2021-10-30 09:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211030_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='long_description',
            new_name='long_description_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='publish_en',
        ),
        migrations.AddField(
            model_name='post',
            name='long_description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات جامع'),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_fa',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
    ]
