# Generated by Django 2.2.15 on 2021-10-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211030_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_en',
            new_name='publish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_fa',
        ),
    ]
