# Generated by Django 2.2.15 on 2021-11-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211031_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='alt_image',
            new_name='alt_image_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_description',
            new_name='meta_description_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_keywords',
            new_name='meta_keywords_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_title',
            new_name='meta_title_en',
        ),
        migrations.AddField(
            model_name='product',
            name='alt_image_fa',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='alt_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_fa',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='meta_description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_fa',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='meta_keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_fa',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='meta_title'),
        ),
    ]
