# Generated by Django 2.2.15 on 2021-09-14 10:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره همراه')),
                ('subject', models.CharField(max_length=500, verbose_name='موضوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=500, verbose_name='موضوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ('created',),
            },
        ),
    ]
